#configs/config.yml

# Data settings
data:
  raw_root: "data/raw"          # Raw data path
  preprocessed_root: "data/preprocessed"  # Preprocessed data save path

experiments_root: "experiments"  # Experiments save path
result_dir: "results"           # Results save path
eda_dir: "eda"                  # EDA save path

# Preprocessing parameters
preprocessing:
  test_size: 0.2
  random_state: 42
  apply_smote: True

# Models configuration
models:
  logistic_regression:
    max_iter: 2000
    #solver: "liblinear"
    #class_weight: "balanced"
  decision_tree:
    max_depth: 10
    class_weight: "balanced"
  random_forest:
    n_estimators: 100
    max_depth: 10
    class_weight: "balanced"
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 10
    random_state: 42
